apiVersion: v1
kind: Service
metadata:
  name: pages-mysql
  namespace: digma-6
  labels:
    app: pages
    tier: database
spec:
  ports:
    - port: 3306
  selector:
    app: pages
    tier: database
  type: ClusterIP